// Catálogo local editable de clubes y selecciones para Jueves de torneo.
// Para actualizarlo, agrega nombres al arreglo y conserva window.FC27_TEAMS.
window.FC27_TEAMS = [
  'AFC Richmond','Ajax','Al Ahli','Al Ahly','Al Ain FC','Al Nassr','Al Hilal','América','Arsenal','AS Monaco','Atlético de Madrid','Atlético Nacional','Aston Villa','Atalanta','Athletic Club','Barcelona','FC Barcelona','Bayern München','Bayer Leverkusen','Bayer 04 Leverkusen','Benfica','Besiktas','Borussia Dortmund','Borussia Mönchengladbach','Brentford','Brighton','Chelsea','Club América','Club Brugge','Celtic','Colo-Colo','Cruz Azul','Deportivo La Coruña','Eintracht Frankfurt','Fenerbahçe','Feyenoord','Flamengo','Galatasaray','Inter','Juventus','LA Galaxy','Leeds United','Liverpool','Lazio','Manchester City','Manchester United','Milan','Monaco','Monterrey','Napoli','Newcastle United','Nottingham Forest','Olympique Lyonnais','Olympique de Marseille','Orlando City','Palmeiras','Paris Saint-Germain','Porto','PSV','Racing Club','Rangers','RB Leipzig','Real Betis','Real Madrid','Real Sociedad','River Plate','Roma','Rosario Central','Santos','Seattle Sounders','Sevilla','Shakhtar Donetsk','Sporting CP','Tottenham Hotspur','Tigres UANL','Toronto FC','Valencia','VfB Stuttgart','Villarreal','Werder Bremen','West Ham United','Wolfsburg','Wolverhampton Wanderers','Wydad Casablanca','Zamalek',
  'Argentina','Brazil','Chile','Colombia','England','France','Germany','Ghana','Italy','Japan','Mexico','Morocco','Netherlands','Portugal','Scotland','Spain','United States','Uruguay',
  'Girona FC','Villarreal CF','Valencia CF','CA Osasuna','Getafe CF','RC Celta','RCD Mallorca','Rayo Vallecano','CD Leganés','Real Valladolid','RCD Espanyol','Albacete BP','Burgos CF','Cádiz CF','CD Castellón','CD Eldense','CD Mirandés','CD Tenerife','Córdoba CF','Elche CF','Granada CF','Levante UD','Málaga CF','Racing Club Ferrol','RC Deportivo','Real Oviedo','Real Racing Club','Real Zaragoza','SD Eibar','SD Huesca','Sporting Gijón','UD Almería','AFC Bournemouth','Crystal Palace','Everton','Fulham','Ipswich Town','Leicester City','Southampton','Blackburn Rovers','Bristol City','Burnley','Cardiff City','Coventry City','Derby County','Hull City','Luton Town','Middlesbrough','Millwall','Norwich City','Oxford United','Plymouth Argyle','Portsmouth','Preston North End','Queens Park Rangers','Sheffield United','Sheffield Wednesday','Stoke City','Sunderland','Swansea City','Watford','West Bromwich Albion',
  'CD Guadalajara (Chivas)','CF Monterrey (Rayados)','Pumas UNAM','Toluca FC','Pachuca CF','Club León','Santos Laguna','Atlas FC','Club Tijuana (Xolos)','Atlético de San Luis','Necaxa','Puebla FC','Querétaro FC','Mazatlán FC','FC Juárez','Inter de Milán','AC Milán','SSC Napoli','AS Roma','Parma','Venezia','Bayern de Múnich','1. FC Heidenheim','SV Werder Bremen','SC Freiburg','1. FSV Mainz 05','FC St. Pauli','Holstein Kiel','AS Mónaco','Stade Brestois 29','OGC Niza','Olympique de Lyon','RC Lens','Olympique de Marsella','Stade de Reims','Stade Rennais','Toulouse FC','Montpellier HSC','RC Estrasburgo','FC Nantes','Le Havre AC','AJ Auxerre','Angers SCO','AS Saint-Étienne',
  'Inter Miami CF','Columbus Crew','Los Angeles FC','New York City FC','New York Red Bulls','Seattle Sounders FC','Atlanta United FC','Philadelphia Union','FC Cincinnati','Orlando City SC','Nashville SC','Houston Dynamo FC','Austin FC','FC Dallas','Sporting Kansas City','Colorado Rapids','Real Salt Lake','Minnesota United FC','Portland Timbers','San Jose Earthquakes','Vancouver Whitecaps FC','CF Montréal','Charlotte FC','St. Louis City SC','Chicago Fire FC','New England Revolution','DC United',
  'Dinamo Zagreb','Hajduk Split','PAOK FC','AEK Atenas','Panathinaikos FC','Olympiacos FC','Dynamo Kyiv','Ludogorets','Omonia','Ferencvárosi TC','HJK Helsinki','Croacia','Bélgica','Ucrania',
  'Deportivo Alavés','Sevilla FC','UD Las Palmas','Bournemouth','Brighton & Hove Albion','Fiorentina','Bologna','Torino','Monza','Genoa','Lecce','Hellas Verona','Udinese','Cagliari','Empoli','Como','TSG Hoffenheim','FC Augsburg','VfL Wolfsburg','1. FC Union Berlin','VfL Bochum','LOSC Lille','Portland Timbers',
  'Brasil','Francia','Inglaterra','España','Alemania','Italia','Países Bajos','México','Estados Unidos','Marruecos'
].filter((team,index,list) => team && list.indexOf(team) === index);
